# BASIC INFO
RP_SITENAME = ENV['RP_SITENAME']
RP_SITEURL  = ENV['RP_SITEURL']

RP_LOGOMARK = 'logo_header_mark.png'
RP_LOGOMAIN = 'logo_header_text.gif'

RP_META_DESC = ENV['RP_META_DESC']

RP_GOOGLE_PLUS_ID 			= ENV['RP_GOOGLE_PLUS_ID']
RP_FACEBOOK_ADMIN_ID 		= ENV['RP_FACEBOOK_ADMIN_ID']
RP_GOOGLE_ANALYTICS_ID 	= ENV['RP_GOOGLE_ANALYTICS_ID']
RP_GOOGLE_ADSENSE_ID 		= ENV['RP_GOOGLE_ADSENSE_ID']

# SITE MAP
RP_SITEMAP_HOST = "http://#{ENV['RP_AWS_ENDPOINT']}"
RP_SITEMAP_PATH = 'sitemaps/'
RP_SITEMAP_FILE = 'sitemap.xml.gz'
RP_SITEMAP_URL  = "#{ENV['RP_AWS_ENDPOINT']}#{RP_SITEMAP_PATH}#{RP_SITEMAP_FILE}"

