
development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: railspress
  username: shunwitter
  password: goodluckcent

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: railspress_test
  username: shunwitter
  password: goodluckcent

production:
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 25
  database: devq77c1a1nvv8
  password: 37lmw4Xws4nue7j11AOaA-WGbr
  username: ryospsabqwnqdv