
development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: railspress
  username: shunwitter
  password: goodluckcent

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: railspress_test
  username: shunwitter
  password: goodluckcent

production:
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 25
  database: 
  password: 
  username: 
